# Site settings
title: Intermediate Games Lab
email: steven@nuclearsandwich.com
baseurl: "/intermediate-browser-games" # the subpath of your site, e.g. /blog/
url: "http://coderdojosv.github.io" # the base hostname & protocol for your site
source_repo: "https://github.com/coderdojosv/intermediate-browser-games"
collections:
  sections:
    output: true

authors:
  - name: Steven! Ragnarök
    github: nuclearsandwich
    email: steven@nuclearsandwich.com


# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
